chore: change color emojis for the color theme picker
googlemaps/android-places-demos pull request #456
Opened 2022-12-16 10:00 UTC by kikoso

This PR changes the emojis of the color theme picker

![color-picker](https://user-images.githubusercontent.com/903097/208073374-33d11324-cebc-4b64-a451-6fc90a373f8a.png)

- [X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #118 🦕

2022-12-16 17:36 UTC, wangela requested changes
Since this feature does not aid in demonstrating Places SDK for Android, how about we remove it altogether? We want to keep the code as minimal as possible to aid in readability for learning use of the SDK.

2022-12-17 07:36 UTC, AndroidDeveloperLB commented
Why is it even here on this sample ? I don't get the point of demonstrating it for a sample of Google Maps...

2022-12-18 10:48 UTC, kikoso commented
Closing this PR, the following one removes completely the theme picker:

https://github.com/googlemaps/android-places-demos/pull/457

2022-12-18 10:48 UTC, closed without merging

2022-12-18 11:16 UTC, AndroidDeveloperLB commented
@wangela I wish all in Google would have your thinking. Sometimes I see such complex samples by Google that even though they look nice, I can't make much benefit from learning there as it's too complicated...